version: "3.9"
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - "database"
    environment:
      PORT: ${PORT}

    restart: always
    networks:
      - app-network

  database:
    build: "./db"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}

    restart: always
    networks:
        - app-network
    
networks:
  app-network:
    driver: bridge    

volumes:
  pgdb:
  logs:
