version: "3.9"
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - "database"
    environment:
      PORT: ${PORT}
    volumes:
      - .logs:/usr/app/logs
    restart: always

  database:
    build: "./db"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./pgdb:/var/lib/postgresql/data/
    restart: always        
